FROM node:22

WORKDIR /app

COPY . .

# Install dependencies and Angular CLI 
RUN npm install --force 
RUN npm install -g @angular/cli 

# Expose the port the app runs on 
EXPOSE 4200

CMD ["ng", "serve", "--host", "0.0.0.0"]